### ISSUE TITLE
Installing filters - best practice for file locations?

### ISSUE THREAD

**Issue by AndyClifton** [jgm/pandocfilters#110]
I've written a filter for pandoc that I would like to use in multiple different file conversions. 

Currently I place the filter in the same directory as the source files, and then call pandoc using something like this:

```shell
$> pandoc ...  --filter filters/name_of_filter
```

where `filters` is a subdirectory.

I'd like to just maintain a single copy of my filters. 

Q: Does pandoc have a default location where it checks for filters where I could deploy my filter? I guess I can choose this myself by giving an absolute path to the filter, but is there a best practice for this?

(apologies if this is out-of-scope for this repo, but I'm not sure where else to ask)

**Comment by jgm** [comment]
You should post this on Discussions at jgm/pandoc.
