### ISSUE TITLE
Sample for graphviz.py

### ISSUE THREAD

**Issue by fjordBob** [jgm/pandocfilters#34]
Hi there,

i play with the graphviz.py filter. My Goal is to write Documents in Atom and use graphviz as diagram engine. I use the "markdown-previe-plus" package to see the preview in Atom. The prerequisites like graphviz and pygraphviz are installed. What i try is to write some markdown and a bit of dot-code. The dot-code looks like this.

``
digraph G {Hello->World}
``

I cant see any graphic in my preview. I tried to "debug" the graphviz.py and i see that the code in this if

``
if key == 'CodeBlock':
``

 never getting reached.

Do you have any kind of sample that will show how to use this Filter?

cheers
-fb

**Comment by jgm** [comment]
See examples/graphviz-sample.md in the repository.

+++ bob fjord [Feb 11 16 09:40 ]:

**Comment by fjordBob** [comment]
Ahh, OK! In my package isnt a graphviz-sample.md.
Works!
Thanks!
