### ISSUE TITLE
Required markdown extension?

### ISSUE THREAD

**Issue by dmckean** [jgm/pandocfilters#35]
It seems that several of the examples use the `backtick_code_blocks` markdown [extension](http://pandoc.org/README.html#extension-backtick_code_blocks). Unless the user enables this, these examples will only work if using the `markdown_github` markdown [variant](http://pandoc.org/README.html#markdown-variants).

**Comment by jgm** [comment]
No, backtick code blocks are enabled by default in pandoc's
markdown.

+++ dmckean [Feb 18 16 19:44 ]:

**Comment by dmckean** [comment]
You're right, my mistake. I was definitely writing poorly-formatted code blocks.
