### ISSUE TITLE
Produced PDF without template style after applying filters

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/pandocfilters#36]
When I run my source through pandoc and apply my latex template on it, it has a certain style. When running through pandoc filters, the style is not there anymore.

I'm not sure how I can describe this better.

I tried to set `--template` for the second call to pandoc (the json -> pdf part) but it results in a latex error (which isn't present without the filters)... 

I'm not sure how to proceed here and hope you can help me.

**Comment by RichardDooling** [comment]
Show the command you use?

On Wed, Mar 9, 2016 at 7:47 AM, Matthias Beyer <notifications@github.com>
wrote:

> When I run my source through pandoc and apply my latex template on it, it
> has a certain style. When running through pandoc filters, the style is not
> there anymore.
>
> I'm not sure how I can describe this better.
>
> I tried to set --template for the second call to pandoc (the json -> pdf
> part) but it results in a latex error (which isn't present without the
> filters)...
>
> I'm not sure how to proceed here and hope you can help me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/pandocfilters/issues/36>.
>



-- 

rd

**Comment by jgm** [comment]
Are you using the --filter option on the command line, or
running the filter manually with pipes?  I'd suggest using
--filter, as it will handle the plumbing for you.

If you do it manually, make sure the --template option is
used on the part that produces your desired output format.
You say this produced an error, but it's difficult to
diagnose without more details.  Perhaps your filter
generates some invalid LaTeX, or LaTeX that requires
a packaging you're not importing?

**Comment by matthiasbeyer** [comment]
@jgm I will test this, though I'm using a `Makefile` and bash script setup to do something like `for filter in $(ls); do...`.

I will check whether the `--filter` option results in what I need.

**Comment by matthiasbeyer** [comment]
Using `--filter` worked. Thanks.
