### ISSUE TITLE
Latest pandoc 1.18 breaks toJSONfilters?

### ISSUE THREAD

**Issue by RichardDooling** [jgm/pandocfilters#50]
I get a key error and the version of pandocfilters.py it uses is old?

File "/usr/local/lib/python2.7/site-packages/pandocfilters.py", line 72, in toJSONFilter
    altered = walk(doc, action, format, doc[0]['unMeta'])

When I use Homebrew to rollback the pandoc to version 1.17 the problem stops.

I'm guessing the new version of pandoc needs also the new version of pandoc filters, but how do I tell Python to load the new one and not the one it's loading?

Thanks for any help.

**Comment by jgm** [comment]
The JSON format changed with 1.18; you need to update to the
latest version of pandocfilters.

    pip install --upgrade pandocfilters

+++ Richard Dooling [Nov 06 16 11:31 ]:

**Comment by RichardDooling** [comment]
That worked like a charm! Thanks, John.

**Comment by ickc** [comment]
Please close this issue, thanks.
