### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by gely** [jgm/pandocfilters#58]
Hi, Would you mind pushing the current version to PyPI? It would be very handy to pip/easy_install to get the latest. I may be an odd case, but my filter does not work without it. Thanks!

**Comment by sergiocorreia** [comment]
I'm a bit confused, as I thought that was the case: 
https://pypi.python.org/pypi/panflute

https://github.com/sergiocorreia/panflute/commit/f645172b0c51cbcce55afbb3ed32f09d2a6dd551

Both have the same version

**Comment by gely** [comment]
Are we mixed up with a different thread from panflute? For pandocfilters, there have been some commits since the last version bump and push to PyPI:

https://pypi.python.org/pypi/pandocfilters/1.4.1

Specifically, this commit is of interest:

https://github.com/jgm/pandocfilters/commit/debaac6fa32ea377441940e9db8c9b28ce34674d

Should I submit a patch for a version bump? I'm not sure how the PyPI process works.

**Comment by sergiocorreia** [comment]
Sorry, for some reason I thought it was a thread on panflute!

About PyPI, jgm needs to upload it so ther is no need to do a PR (on panflute, that's done by TravisCI every time a new version passes all the tests).

On the mean time, perhaps you can pip install from github?

```
pip install git+git://github.com/jgm/pandocfilters.git
```

**Comment by gely** [comment]
Good idea, thanks. I will do that for now.

**Comment by ickc** [comment]
@jgm, if you would like getting help on the distribution aspect of maintaining pandocfilters, I would like to offer help. I could also help on screening the pull requests if you don't mind.

**Comment by jgm** [comment]
I've uploaded a new version to PyPi. @ickc, let me know if I'm doing anything wrong.
