### ISSUE TITLE
Issues in Python 3.6.5

### ISSUE THREAD

**Issue by Evidlo** [jgm/pandocfilters#70]
It seems that pandocfilters has problems with Python 3.6.5.
``` bash
[evan@blackbox examples] python --version
Python 3.6.5
[evan@blackbox examples] pip freeze | grep pandocfilter
pandocfilters==1.4.2
[evan@blackbox examples] ~/resources/pandoc-2.2.2.1/bin/pandoc test.md -t json --filter ./caps.py
Error running filter ./caps.py:
Error in $: Failed reading: satisfy
```

The same filter works fine in Python 2.7.
``` bash
[evan@blackbox examples] python --version
Python 2.7.15
[evan@blackbox examples] pip freeze | grep pandocfilter
pandocfilters==1.4.2
[evan@blackbox examples] ~/resources/pandoc-2.2.2.1/bin/pandoc test.md --filter ./caps.py
<h1 id="hello">HELLO</h1>
<p>WORLD</p>
```

Both examples were run with the latest release of pandoc.  `test.md` is include below.

``` markdown
# hello

world
```

**Comment by jgm** [comment]
Strange. It works for me, with both python versions,
so I'm not sure what might be going on.

Are ryou sure that the same version of pandocfilters
is installed for python2 and python3?

(On my system, pip is python2 and pip3 is python3.)
