### ISSUE TITLE
pandoc_markdown to gitlab_markdown filter

### ISSUE THREAD

**Issue by pfortho** [jgm/pandocfilters#74]
Thanks for the example on gitlab. But is there also a visa versa case possible __pandoc_markdown__ to __gitlab_markdown__.

going from:

        $$ \frac{1}{T \cdot p} $$

to 
```
    ``` math
    \frac{1}{T \cdot p}
    ```
```

Any help would be appreciated.

**Comment by jgm** [comment]
This doesn't seem to be an issue report. If you have questions about pandoc (including filters), please use the pandoc-discuss mailing list (google groups).
