### ISSUE TITLE
Common Place to store pandoc filter

### ISSUE THREAD

**Issue by innomadic** [jgm/pandocfilters#78]
Perhaps I am missing something, but it seems like even to use the provided example filters I need to do an absolute path reference to my pip sitepackages or copy the filter into the various places in which we will use it.

Is it possible to "install" a filter and access it no matter from which folder I call it?

**Comment by jgm** [comment]
Make it executable and put it in your path.

**Comment by innomadic** [comment]
@jgm Thanks so much for the pointer.  I made a scripts/pandoc folder, chmod u+x on the filter file, and it works.  

Thanks for the wonderful tool
