### ISSUE TITLE
Python instance of top-level Pandoc object

### ISSUE THREAD

**Issue by gwgundersen** [jgm/pandocfilters#84]
I am trying to replicate [this Pandoc filter](https://gist.github.com/mathematicalcoffee/e4f25350449e6004014f), which appears to manipulate a top-level AST `Pandoc` object. See documentation [here](https://hackage.haskell.org/package/pandoc-types-1.20/docs/Text-Pandoc-Definition.html#t:Pandoc). Does this Python package having an equivalent object? I cannot find it. Alternatively, is there a way to insert into the top of the AST tree? Thanks.

**Comment by jgm** [comment]
Sorry, no.  You might check out panflute, which is a more fully featured library for doing the same thing.

**Comment by gwgundersen** [comment]
Okay, thanks for the quick reply.
